# Generated by Django 3.2.20 on 2023-08-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230817_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingeredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='core.Ingredient'),
        ),
    ]
